# Establece la imagen base
FROM node:14 as build

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos
COPY . .

# Construye la aplicación React
RUN npm run build

# Establece la imagen base para el contenedor final
FROM nginx:alpine

# Copia los archivos de construcción en la carpeta de Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80

# Ejecuta Nginx
CMD ["nginx", "-g", "daemon off;"]
