version: '3'

services:
  app:
    image: node:18.15.0
    volumes:
      - ./server:/home/node/app/server
      - ./client:/home/node/app/client
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - 3000
      - 3001
    working_dir: /home/node/app
    command: >
      /bin/bash -c "
      tail -f /dev/null
      "
    user: "1000:1000"
    
    

 

      
