# Establece la imagen base
FROM node:14

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos
COPY . .

# Expone el puerto 5000
EXPOSE 5000

# Ejecuta el servidor
CMD ["npm", "start"]